apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myuser
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZhbUYwYVc0d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDVElNWXZjWDB0VWFyTUJmNSttMXhGeHNmNW16QVp6T0ZVK3V4L2FwK21ZWkxzClpSd0c2VFVzVTA3cHNKd01HY01xTllXbUxJZkJSNVVseE83djNablNRWVJtYkRid2daSkNyTS9XNnhXYjl3N0QKejluTGxrVVJMeC80czFjaEJyaHgvbWZhaGFvZENYZzNwTUFwaEovU1N0cmRoVS9GRlRYTjg2MEFRYWJxVHVvNQpKUEpJdzNVT1VJRXRyUUhPcjJHSWVMQ01ERmIzb3V4TzE1eUx1VlpXZWU5NERsdUdBK2FTS0ZtdmpQbm9LbWRXCmFNT25hL3BBTGxneTlueEhyaUpwZXViNitJRnNVUlUxSEpER1FvR1hrUnJkQ3ZDTUVuczM5aHhEbm1JYzYyekMKdUw3NmhhU1BkZ2JjL0ZldzNaaEExN2Z1aEpaQmh4ajVsUm9YQ3BoM0FnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFjZXg5Wm1qSGNhSTR1bDA5V1lLQjVkTXJxUjVHcG9nSXFQcURMYjJvNUc0T0h1NTJ6UWs3ClE4aEZqN1N6RzErMG5Ndmh0WnJWbiswd3hicFlxdk5yV2lDSlBlY0dFMEg4S00rSHFUVnFheXhKbExoY2cwMkwKYVVlOHMweHlzV3ZtQzBiR0hJK1g1YkliSFdIMUhBc0ZKQkVXR1lDSE5keC9rTm1JaERzdldHQmhzWTNTR3RrNwo5c2hMN3FidFptSzFoZzM0TG1ZNG92Mm03QU5sTEszMUgxc3hBdDI1SE5waUNVTkZ2UXRyUW8zMXZRR1N2TDErCjFNSitmc01vNG16T2Z1M0ZtSC8wS3lMaEdVaTdBaU9TMVhoUzdlK3lpOUgxc29Nci90V1ZhZHI5ZGxDUmtiOXMKQlI3ZitVTi9XRDdVWWMyUlUvUmVnYTFaeEZldjhpQWc2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
  - client auth


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-roleBind
  namespace: default
subjects:
- kind: User
  name: jatin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-role 
  apiGroup: rbac.authorization.k8s.io

----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA3sTk5x/kWmsAuI14QZsnjCaxjOBwsjsZj1+PJo6CCOxpew//
l6X0y/0XNoli4wRIQXZQFkvFn22fUbrsWNuHYKrQdiwpZnSMeG/nvCexlm0gNUPv
kpSc3GM0SJOixLHvOzwJahL87paMaEsReIl2sUYAlTdPAds2f+DiCbL3BV7bBCXr
v6s0yIjs9iUB9ROiPet1bssrh9XTi0dIGu2Cof95GYLxJJryDTdDe7fKukkvy1mY
/REuxt//G2SIU/vJ3V1Cbs9C4RpEv3dbRaEskXkAS4rkfMm39zxjouX4becxQUUv
s1/mZ2ayzPkNrip7KN/zHMdXNvtdMNhLoNArGQIDAQABAoIBAGUCOhhiaZRl+Em2
O9TjmSb/VHpgOjlWetx7o9kDvQp2x805D9efNERaWfAsk14ETw7/qoixisYjWp4g
d5JC2DuIuEUc+RivuBHUC+tQxEFE8dm1GCgKoqV7hfVym9c8JxFgw5QJUA6OzNNt
VlqlWeA/sXv3PCfHUgrh2Rw0vbT82QoRvHSVpU20m/FFLZESbs7URf08vvzyhfeg
Jv5cBBaQD1GUxNBY5oRK9u0PVUlABm+MDgg4ER0Z+u6MavZBrAbqzzBpTeqHyXAy
zM6Hj9gY8IJSd/qvdldSsKYB4kszKkmJoMbCaOU9AP0YWT27CQmVghwi336kif4C
PL1TcEECgYEA9ISW86nBH736NCgxy1Wf09fkcM9KfKBoqqcMiw0jIqJ5dU/XeWpD
9pV+FLPWoWOMkkbgAtEMtRBInDHI4Fu+kKuUOWOdbbkc5uH9t3eW+pRjQGLjr0iF
vVLADjDu/V/Vq1+BeB9vaLOxPj51/Gy7PSR8he+WSvzQ9gyHTrUx090CgYEA6Trb
T0hhKHtlZASPDKqMYH8EvJbu4gcDRl7ReflUgJMcyygWlPCiHSipD/lGavqvHCAk
SR43MDxEi5rN/Q/N1JoauIS6r5jC2sf4aGtp1aPT9g0V8OU4W3v8oH34JlOqBzPZ
D+T1+RrLoMjf/BRb68qT6efrX6zYw0PGpMbQbm0CgYEA56N38Usedjid/60YRv1N
lP2QHsJxWREJNqlb+5qtb1El6NmDUjU2PzItp+UabfeFoslby69I73qGntmW59xh
8mFo4NkauWhFFgB/P8AeGjJauBM2iMYWVF1BLfBzZzrTiy7F0wtMmo6oWUQIt+I1
mt2mzadD5LQOLRl/UTPcCU0CgYEAwuJlYwhN9y+09zBAAAt6pR897AAKuF+3wtN0
IoHOtGk5BCEJTYcNT2QscKaQys+SBuRsrZRL9UhG1oiSW0Ubbu0eKtTt0dDJ8Vpr
HYWzt8rfUJh6nwJKZ1dhLxJTimMajk4qsHdXecGEKWPwlYjFjm+FzUv3h8i8j91Q
XVuryrkCgYA/U+m2jtIAc525H12FP+gho5tTGvCBJGRkKl1LPLfwjN0mBlRVRq7i
lmbFJM2PXe8Fl8sc2BgpP7ccKZfQJloCq5hSGK1yXggiaFPSXyugiJNRGEPV88vn
YKi8bojNGZDAftyM3E+m15KcLtCZvVoieWwRybd+obG60aRRmjsF2g==
-----END RSA PRIVATE KEY-----

-----BEGIN CERTIFICATE-----
MIIDBTCCAe2gAwIBAgIID0PHgzm08IYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0yNDA5MzAwODU2MDZaFw0zNDA5MjgwOTAxMDZaMBUx
EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDexOTnH+RaawC4jXhBmyeMJrGM4HCyOxmPX48mjoII7Gl7D/+XpfTL/Rc2
iWLjBEhBdlAWS8WfbZ9RuuxY24dgqtB2LClmdIx4b+e8J7GWbSA1Q++SlJzcYzRI
k6LEse87PAlqEvzuloxoSxF4iXaxRgCVN08B2zZ/4OIJsvcFXtsEJeu/qzTIiOz2
JQH1E6I963VuyyuH1dOLR0ga7YKh/3kZgvEkmvINN0N7t8q6SS/LWZj9ES7G3/8b
ZIhT+8ndXUJuz0LhGkS/d1tFoSyReQBLiuR8ybf3PGOi5fht5zFBRS+zX+ZnZrLM
+Q2uKnso3/Mcx1c2+10w2Eug0CsZAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ2+kG5P5Mzlw2ucMEkVRi5eKQtKzAV
BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQDX7W/hDqXe
nU++aKqgfeAo7n+gl+U6zBP0b6pA5MyuB4Kl3VRFzCMkRZXR0xYSF5Pcq7RqHKVa
Rqpye2Oi/vJpk/IJBDB3yPPp/3iK2HI+C0dDPpQCxY9h4x4tkSDO6fUlO2korxUB
qpFrzAXNo8+08nFx5lw1za6QORZ/Gv22ea4NvmsYmQq3ZZ7PNZhAuT333PJp87xe
80cjRiYjiMfG+QB9bei6b9uIi2iNWKidgm++kBIgq+MVp/RT0FQPOYBKaBIE4hKg
HRm8oa+GYeQCjW8dDZj1tHAmQeptCV4McT+uRFT8dQiv7Z2AmoMrL+pbtYXEsRel
e5/IMHvQQ/Vl
-----END CERTIFICATE-----

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: aryan
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZZWEo1WVc0d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFEZ1ExbUpseFQwbW1MdUNjai8vZ2krZkUwQm5OVXVySXdLTFFvUGNGaGd4V2pkCnJOb1ZiY0V0aHRWTVRxUUNtT0lWcjVraW10WnF6Sjdsb0R0STQzbmlISHpXWW56UE04TE9tTHhhb2RyV0FLWTAKdEZpS3NVWWlWY0xDWEo5MHdBRnZnMUp4NTZ6VVNDNmZOdWl3dVdvSzgyRmFRMHd3OHZIT01wRFdCd09ZRCtBNgpEY0NrUnEzSTZTaFJiYlgvc1QzT1FjYm5qUFBUVkJxZ3gwNm5KZ2N5dnZnbGNlZDJCeHJhNmw1cVlhRVdMOUtUClI3b29rcUQranFyWlZXREwvNjdFYUtLRnpQblNjODY5WU8rWXhWdVNmN0hUdlpOcXM4aGwvRExLaHpVRy9iV3AKU2FBQzZTU3c5V3dwNTZZa093YmJEVTVFa1pmYUpXWUdLOWJKOUNFaEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFBejVZcWZzUzVvKzBIKzJjM3dOTE9NRWJrQWxlcGlmWlQ3OUs4ZkltdkxTS2NvSlZkV2RFClRrNTIzUVlvbW1kU3ZkdmowTWhqekliak45TnlMdFpGNWJhQTNJaWlwQjU1eFUzbVU3OWQvWW43M1A4akFYYk8KQTlIVWk4SGtwVTAvdGFlQ3hrbzJ0YlQzTHpJYUNZMmFWUWduREJ6ZzJ2VERCZjd0T09YUUhPOGdGaEMvenY1bQp0VHJVSyt0N1pZcUtWaHowdTRNK2pvMzdnUmtiVWVLcTd3dnV6bDkvd21YTnAvSGUzNVZRaGJzMitocjN4RGZ1CnJKOFh1Y0UxaU9xMmpsWU82NUtSdHZSdCtBczhhR2ZpZWc3QzNWaFk4UHJGQ2JEVkF2SndINGhkZnRIQTFwNnMKS2tNYTBKQzdNeFBaT2o3ZW1lQVJNaXphRGJVVTJIRlhqZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400000  
  usages:
  - client auth
