apiVersion: apps/v1
kind: Deployment
metadata:
  name: manav-nginx-custom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
        - name: nginx-custom
          image: 345594592951.dkr.ecr.ap-south-1.amazonaws.com/manav/manav-repo:latest
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-task1
   annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"  
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-custom

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-task1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"  
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-custom      
