apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-task2
  labels:
    app: nginx-deploy-task2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-task2
  template:
    metadata:
      labels:
        app: nginx-task2
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: Manav-NodeGroup
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume-manav
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config-volume-manav
        configMap:
          name: manav-new

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa-task2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment-manav
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-task2
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"  
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-task2


helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  --set clusterName=EKS-Hackathon-Sept24 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  --namespace kube-system

helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  --set clusterName=Manav-EKS \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  -n kube-system

